### ISSUE TITLE
Missing data.jl 

### ISSUE THREAD

**Issue by mohamed82008** [TuringLang/TuringBenchmarks#4]
https://github.com/TuringLang/TuringBenchmarks/blob/46b5fde12c55fa23d9c4b94003e032f67b34068f/negative_binomial.benchmark.jl#L4

Some files include a file `data.jl` but I can't seem to find it.

**Comment by yebai** [comment]
@xukai92 @hessammehr any thoughts where this might be?

**Comment by xukai92** [comment]
From the benchmark name I guess this should be a Julia version of this https://github.com/stan-dev/example-models/blob/master/basic_estimators/negative_binomial.data.R

**Comment by mohamed82008** [comment]
I think that could be an old reference to https://github.com/TuringLang/TuringExamples/blob/master/stan-models/negative_binomial.data.jl

**Comment by mohamed82008** [comment]
More missing files https://github.com/TuringLang/TuringBenchmarks/blob/46b5fde12c55fa23d9c4b94003e032f67b34068f/gauss.run.jl#L6. I can't find the toy-problems folder.
