### ISSUE TITLE
Setup Travis and AppVeyor

### ISSUE THREAD

**Issue by mohamed82008** [TuringLang/TuringBenchmarks#6]
This packages needs Travis and AppVeyor turned on.

**Comment by mohamed82008** [comment]
The files are in the PR.

**Comment by yebai** [comment]
I have turned on `Travis`. 

Do we actually want to run benchmarks `AppVeyor`? It's pretty slow.

**Comment by mohamed82008** [comment]
Not necessarily. I can remove it.
