### ISSUE TITLE
Replacing mlab with local JSON file

### ISSUE THREAD

**Issue by mohamed82008** [TuringLang/TuringBenchmarks#9]
This issue discusses the tentative plan for replacing the use of mlab with a local benchmarking results file and [GitHub.jl](https://github.com/JuliaWeb/GitHub.jl). The way it can be used is as follows. Firstly, we will need a new Github account with public credentials. Using GitHub.jl, this account can be used to clone TuringBenchmarks, make a new branch, run benchmarks, save results, add and commit them, push to remote branch and create a PR to the main TuringBenchmarks repo. This process will be automated in the test script of Turing PRs.

So the dummy account will have TuringBenchmarks in its repos, and when a new PR in Turing is made, and the Travis test script is run, we:
1. Configure the public Github account on the Travis machine,
2. Clone the TuringBenchmarks package locally,
3. Add the TuringBenchmarks remote,
4. Create a new branch locally
5. Run the benchmarks using Turing and TuringBenchmarks,
6. Query the current branch and commit of Turing,
7. Append the results to a JSON file in TuringBenchmarks including branch, commit, time, etc., 
8. Add and commit the changes, and push to a remote branch,
9. Make a PR to the main TuringBenchmarks repo referencing the commit and branch of Turing tested.

Additionally, at the beginning we can check which branches have been merged already and delete them. All of this will be programmed in a function in TuringBenchmarks so it can be conveniently run from the Turing Travis script.

Feedback is welcome!

**Comment by mohamed82008** [comment]
Much of this is already implemented in Nanosoldier.jl. And using a Github app is a more appropriate way of doing the above to avoid the dummy Github account.

**Comment by yebai** [comment]
`Nanosoldier.jl` looks good. It would be good to adapt it for Turing benchmarks.
